language: python
dist: xenial

python:
  - "3.6"

env:
  - DJANGO=1.11.16

install:
  - pip install Django==$DJANGO
  - python setup.py install
  - pip install codecov

script: python `which django-admin.py` test --settings=django_rq_wrapper.tests.settings
services: redis

after_success:
  - codecov
