language: python
dist: xenial

python:
  - "3.6"

env:
  - DJANGO=1.11.16

install:
  - pip install Django==$DJANGO
  - python setup.py install

script: python `which django-admin.py` test django_rq_wrapper --settings=django_rq_wrapper.tests.settings
services: redis
